### ISSUE TITLE
Http get 

### ISSUE THREAD

**Issue by bwhite80** [jackw01/led-control#35]
Is there an HTTP GET request for the web interface? There is a 3rd party plugin that sends GET requests to change settings.

**Comment by Fitipalek** [comment]
check app.py , there are all requests that i know of :)

**Comment by jackw01** [comment]
The APIs used internally by the web interface have changed in version 2.0.0. The major version number was incremented because this version includes breaking changes, and this was stated in the release notes. If your issue is with compatibility with someone else's software, please use a 1.x.x version and/or contact the developers of the other software.
